[project]
name = "src"
version = "0.0.1"
description = "An MLOps project for productionising vehicle insurance model"
authors = [{name = "Amman Sajid", email = "ammansajid1@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}